// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $dashboard_iteration1 from "./routes/dashboard/iteration1.tsx";
import * as $dashboard_iteration10 from "./routes/dashboard/iteration10.tsx";
import * as $dashboard_iteration2 from "./routes/dashboard/iteration2.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/dashboard/iteration1.tsx": $dashboard_iteration1,
    "./routes/dashboard/iteration10.tsx": $dashboard_iteration10,
    "./routes/dashboard/iteration2.tsx": $dashboard_iteration2,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
